version: '3'

services:
    db:
        build: ./db
        env_file:
            - ./db/.env
        ports:
            - 5432:5432            
    app:
        build: ./app
        container_name: dog_app
        entrypoint: tail -f /dev/null
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./app/.env
